---

- name: Install GCC
  yum:
    name: gcc
    pdate_cache: yes
    state: installed

- name: Download Python 2.7
  unarchive:
    src: https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
    dest: /tmp/python27
    remote_src: yes

- name: configure python 2.7.10
  command: ./configure; make install
  args:
    chdir: "/tmp/python27"

- name: make and install python 2.7.10
  become: yes
  shell: make && make install
  args:
    chdir: "/tmp/python27"

- name: recycle python install file
  command: rm -rf /tmp/python27

- name: Install pip
  become: yes
  yum:
    name: 
      - python-pip 
      - python-wheel
    state: present
- name: Install kubespray python depencies
  become: yes
  pip:
    name:
      - netaddr
      - Jinja2